package com.aiassistant.core.domain.inference

object MultiStagePrompts {
    const val CLASSIFICATION_CONTRACT = """Use only explicitly stated facts and never invent symptoms. First identify candidate categories from their semantic definitions, then evaluate evidence relative to each candidate. Supporting evidence directly establishes the selected category. Contradicting evidence is a fact directly incompatible with the selected category; a fact that merely excludes an alternative category is not contradicting evidence. Use SUPPORTED for one specific category with non-empty supporting evidence and no contradicting evidence. Use INSUFFICIENT with AMBIGUOUS when no category has enough direct support. Use CONFLICTING with AMBIGUOUS only for direct supporting and contradicting evidence about the same candidate, or for genuinely incompatible causes that each have direct support; both evidence lists must be non-empty. Category definitions: NETWORK_UNAVAILABLE means network connectivity is explicitly unavailable; OPENAI_RATE_LIMIT means the remote AI service explicitly rejected requests because its request quota or rate was exceeded; OPENAI_TIMEOUT means the remote AI request explicitly exceeded its allowed response time; EMPTY_AI_RESPONSE means the AI request completed but returned no usable content; LOCAL_HISTORY_UNAVAILABLE means locally stored chat history explicitly cannot be loaded; AMBIGUOUS means facts are insufficient or genuinely conflicting. Required actions: NETWORK_UNAVAILABLE -> CHECK_NETWORK; OPENAI_RATE_LIMIT -> RETRY_WITH_BACKOFF; OPENAI_TIMEOUT -> RETRY_REQUEST; EMPTY_AI_RESPONSE -> SHOW_EMPTY_RESPONSE_ERROR; LOCAL_HISTORY_UNAVAILABLE -> RELOAD_LOCAL_HISTORY; AMBIGUOUS -> REQUEST_MORE_INFORMATION. Confidence must be a JSON number from 0 to 1, never a percentage."""
    const val MONOLITHIC = "Classify the incident using this contract: $CLASSIFICATION_CONTRACT Then write a concise Russian user response. Return exactly one JSON object matching the schema, with no markdown or surrounding text."
    const val NORMALIZATION = "Extract only explicitly observed facts and a non-empty normalized summary. Do not classify, select an action or severity, produce category-relative evidence, or write a response. Return exactly one JSON object matching the schema, with no markdown or surrounding text."
    const val DECISION = "Decide only from the supplied validated normalized facts using this contract: $CLASSIFICATION_CONTRACT Return exactly one JSON object matching the schema, with no prose, markdown or surrounding text."
    const val PRESENTATION = "Write concise Russian title, message and user_action from the supplied summary and decision. Do not change or mention the decision or pipeline stages. Return exactly one JSON object matching the schema, with no markdown or surrounding text."
    const val VALIDATION_CORRECTION = "The previous response failed structural or domain validation. Re-evaluate the same input and return one corrected JSON object matching the schema. Do not use markdown or surrounding text."
}
